// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: twofa.proto

package twofapb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TwoFAServiceClient is the client API for TwoFAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwoFAServiceClient interface {
	GenerateTwoFACode(ctx context.Context, in *TwoFAPayload, opts ...grpc.CallOption) (*empty.Empty, error)
}

type twoFAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwoFAServiceClient(cc grpc.ClientConnInterface) TwoFAServiceClient {
	return &twoFAServiceClient{cc}
}

func (c *twoFAServiceClient) GenerateTwoFACode(ctx context.Context, in *TwoFAPayload, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/twofa.TwoFAService/GenerateTwoFACode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwoFAServiceServer is the server API for TwoFAService service.
// All implementations must embed UnimplementedTwoFAServiceServer
// for forward compatibility
type TwoFAServiceServer interface {
	GenerateTwoFACode(context.Context, *TwoFAPayload) (*empty.Empty, error)
	mustEmbedUnimplementedTwoFAServiceServer()
}

// UnimplementedTwoFAServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTwoFAServiceServer struct {
}

func (UnimplementedTwoFAServiceServer) GenerateTwoFACode(context.Context, *TwoFAPayload) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateTwoFACode not implemented")
}
func (UnimplementedTwoFAServiceServer) mustEmbedUnimplementedTwoFAServiceServer() {}

// UnsafeTwoFAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwoFAServiceServer will
// result in compilation errors.
type UnsafeTwoFAServiceServer interface {
	mustEmbedUnimplementedTwoFAServiceServer()
}

func RegisterTwoFAServiceServer(s grpc.ServiceRegistrar, srv TwoFAServiceServer) {
	s.RegisterService(&TwoFAService_ServiceDesc, srv)
}

func _TwoFAService_GenerateTwoFACode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoFAPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwoFAServiceServer).GenerateTwoFACode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twofa.TwoFAService/GenerateTwoFACode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwoFAServiceServer).GenerateTwoFACode(ctx, req.(*TwoFAPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// TwoFAService_ServiceDesc is the grpc.ServiceDesc for TwoFAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwoFAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "twofa.TwoFAService",
	HandlerType: (*TwoFAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTwoFACode",
			Handler:    _TwoFAService_GenerateTwoFACode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twofa.proto",
}
